/**
 * @file agent_manager.cpp
 * @brief Implementation of the local agent action execution engine.
 *
 * This file implements the AgentActionManager class, responsible for 
 * validating agent requests against a security whitelist and safely 
 * executing approved local file system operations.
 */

#include "agent_manager.h"

#include <QFile>
#include <QTextStream>

/**
 * @brief Constructs the Action Manager.
 */
AgentActionManager::AgentActionManager(QObject* parent) : QObject(parent) {
    // Constructor initialized via initializer list in header
}

/**
 * @brief Adds a specific action string to the permitted security whitelist.
 */
void AgentActionManager::addWhitelistedAction(const QString& action) {
    whitelistedActions.insert(action);
}

/**
 * @brief Verifies if the LLM's requested action is permitted by the system.
 */
bool AgentActionManager::isActionWhitelisted(const QString& action) const {
    return whitelistedActions.contains(action);
}

/**
 * @brief Executes a system-level command after user approval via the UI modal.
 */
bool AgentActionManager::executeApprovedAction(const AgentCommand& command) {
    // Secondary security check to ensure the action is explicitly whitelisted
    if (!isActionWhitelisted(command.action)) {
        return false;
    }

    // --- Route 1: Write File ---
    if (command.action == "write_file") {
        QFile file(command.target);
        
        // Open the file in write-only text mode (this creates it or overwrites existing content)
        if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
            QTextStream out(&file);
            
            // Write the exact string payload generated by the LLM into the file
            out << command.payload;
            
            file.close();
            return true;
        }
    }

    // Return false if the action fails or is an unrecognized native command
    return false;
}