[Setup]
; Basic application details
AppName=Gemini Native Agent
AppVersion=1.0.0
AppPublisher=Lewis Curl
AppPublisherURL=https://github.com/Eric904P/gemini_cli_gui

; Default installation directory (e.g., C:\Program Files\Gemini Native Agent)
DefaultDirName={autopf}\Gemini Native Agent
DefaultGroupName=Gemini Native Agent

; Output settings for the final installer
OutputDir=C:\dev\gemini_cli_gui\installer_output
OutputBaseFilename=GeminiAgent_Setup_v1.0.0
Compression=lzma2/ultra64
SolidCompression=yes

; Required privileges
PrivilegesRequired=admin

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The core executable
Source: "C:\dev\gemini_cli_gui\build\GeminiCliGui.exe"; DestDir: "{app}"; Flags: ignoreversion

; Grab ALL the DLLs and folders generated by windeployqt
Source: "C:\dev\gemini_cli_gui\build\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Create shortcuts in the Start Menu and Desktop
Name: "{group}\Gemini Native Agent"; Filename: "{app}\GeminiCliGui.exe"
Name: "{group}\{cm:UninstallProgram,Gemini Native Agent}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Gemini Native Agent"; Filename: "{app}\GeminiCliGui.exe"; Tasks: desktopicon

[Run]
; Option to launch the app immediately after installation
Filename: "{app}\GeminiCliGui.exe"; Description: "{cm:LaunchProgram,Gemini Native Agent}"; Flags: nowait postinstall skipifsilent